name: Issue Event Logger
on: issues
jobs:
    log-issue-details:
        runs-on: ubuntu-latest
        steps:
            - name: output event details
              run: echo "${{ toJson(github.event) }}"
            